language: python
python:
  - 2.7
cache: pip
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install --allow-external dirspec --allow-external u1db --allow-unverified dirspec --allow-unverified u1db -r pkg/requirements.pip
  - pip install -r pkg/requirements-testing.pip

  # Based on http://stackoverflow.com/questions/24489588/how-can-i-install-pyside-on-travis
  - sudo apt-get install libqt4-dev
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

script:
  - sh pkg/postmkenv.sh
  - python setup.py test

after_success:
  coveralls

notifications:
  email: false