language: python
python:
  - 2.7
  - pypy
install:
  - "pip install -r pkg/requirements.pip"
  - "pip install -r pkg/requirements-testing.pip"
script: "python setup.py test"
notifications:
  email: false